@startuml
package CPP_Maps {
    class Map {
    displayMap()
    displayDirections()
    }

    class Navigation {
    ArrayList<Locations> route
    findBestPathUsingDijkstras(start, end)
    }

    class SearchEngine {
    searchByName()
    searchByCategory()
    }


    class Place {
    name
    location
    category
    }

    class Location {
    coordinates
    }

    class Category {
    categoryName
    }


    Map --|> Location
    Map -- Navigation

    Navigation --|> Location
    SearchEngine --|> Place

    Place o-- Location
    Place o-- Category
}

interface App {
sendLocation(location)
}

Navigation --|> App

@enduml


